---
template_path: ec2/route_table.yaml.j2

sceptre_user_data:
  project_code: "{{stack_group_config.project_code}}"
  source_repo_url: "{{source_repo_url}}"
  source_repo_branch: !environment_variable SOURCE_REPO_BRANCH
  route_tables:
    - name: RouteTablePublic
      tags:
        Name: {{part}}-RouteTable-Public
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
      route_entries:
        - name: DefaultIPv4
          destination_cidr_block: 0.0.0.0/0
          gateway_id: !stack_output {{pwd}}/ec2-internetgateway.yaml::InternetGateway
    - name: RouteTablePrivateA
      tags:
        Name: {{part}}-RouteTable-Private-A
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
    - name: RouteTablePrivateB
      tags:
        Name: {{part}}-RouteTable-Private-B
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
