---
template:
  path: ec2/internet_gateway.yaml.j2

sceptre_user_data:
  project_code: "{{stack_group_config.project_code}}"
  source_repo_url: "{{source_repo_url}}"
  source_repo_branch: !environment_variable SOURCE_REPO_BRANCH
  internet_gateways:
    - name: InternetGateway
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
      tags:
        Name: "{{part}}"
