---
template:
  path: ec2/network_acl.yaml.j2

sceptre_user_data:
  project_code: "{{stack_group_config.project_code}}"
  source_repo_url: "{{source_repo_url}}"
  source_repo_branch: !environment_variable SOURCE_REPO_BRANCH
  nacls:
    - name: NetworkAclPublicSubnet
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
      tags:
        Name: {{part}}-NACL-Public
      nacl_entries:
        - rule_number: 10100
          rule_action: allow
          direction: ingress
          protocol: -1
          cidr_block: !stack_output {{pwd}}/ec2-vpc.yaml::VPCCidrBlock
        - rule_number: 10200
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 6
          port_range:
            from: 1024
            to: 65535
        - rule_number: 10300
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 17
          port_range:
            from: 1024
            to: 65535
        - rule_number: 11000
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 6
          port_range:
            from: 80
            to: 80
        - rule_number: 11010
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 6
          port_range:
            from: 443
            to: 443
        - rule_number: 30100
          rule_action: allow
          direction: egress
          protocol: -1
          cidr_block: 0.0.0.0/0
    - name: NetworkAclPrivateSubnet
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
      tags:
        Name: {{part}}-NACL-Private
      nacl_entries:
        - rule_number: 10100
          rule_action: allow
          direction: ingress
          protocol: -1
          cidr_block: !stack_output {{pwd}}/ec2-vpc.yaml::VPCCidrBlock
        - rule_number: 10200
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 6
          port_range:
            from: 1024
            to: 65535
        - rule_number: 10300
          rule_action: allow
          direction: ingress
          cidr_block: 0.0.0.0/0
          protocol: 17
          port_range:
            from: 1024
            to: 65535
        - rule_number: 30100
          rule_action: allow
          direction: egress
          protocol: -1
          cidr_block: 0.0.0.0/0
