---
template:
  path: ec2/subnet.yaml.j2

sceptre_user_data:
  project_code: "{{stack_group_config.project_code}}"
  source_repo_url: "{{source_repo_url}}"
  source_repo_branch: !environment_variable SOURCE_REPO_BRANCH
  subnets:
    - name: SubnetPublicA
      cidr_block: "!Select [0, !Cidr [!ImportValue vpcdemo-{{pwd}}-ec2-vpc-VPC-CidrBlock,4,8]]"
      availability_zone: "{{stack_group_config.region}}a"
      tags:
        Name: {{part}}-Public-Subnet-A
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
      map_public_ip_on_launch: True
      network_acl_id: !stack_output {{pwd}}/ec2-networkacl.yaml::NetworkAclPublicSubnet
      route_table_id: !stack_output {{pwd}}/ec2-route.yaml::RouteTablePublic
    - name: SubnetPublicB
      cidr_block: "!Select [1, !Cidr [!ImportValue vpcdemo-{{pwd}}-ec2-vpc-VPC-CidrBlock,4,8]]"
      availability_zone: "{{stack_group_config.region}}b"
      tags:
        Name: {{part}}-Public-Subnet-B
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
      map_public_ip_on_launch: True
      network_acl_id: !stack_output {{pwd}}/ec2-networkacl.yaml::NetworkAclPublicSubnet
      route_table_id: !stack_output {{pwd}}/ec2-route.yaml::RouteTablePublic
    - name: SubnetPrivateA
      cidr_block: "!Select [2, !Cidr [!ImportValue vpcdemo-{{pwd}}-ec2-vpc-VPC-CidrBlock,4,8]]"
      availability_zone: "{{stack_group_config.region}}a"
      tags:
        Name: {{part}}-Public-Private-A
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
      network_acl_id: !stack_output {{pwd}}/ec2-networkacl.yaml::NetworkAclPrivateSubnet
      route_table_id: !stack_output {{pwd}}/ec2-route.yaml::RouteTablePrivateA
    - name: SubnetPrivateA
      cidr_block: "!Select [3, !Cidr [!ImportValue vpcdemo-{{pwd}}-ec2-vpc-VPC-CidrBlock,4,8]]"
      availability_zone: "{{stack_group_config.region}}b"
      tags:
        Name: {{part}}-Public-Private-B
      vpc_id: !stack_output {{pwd}}/ec2-vpc.yaml::VPC
      network_acl_id: !stack_output {{pwd}}/ec2-networkacl.yaml::NetworkAclPrivateSubnet
      route_table_id: !stack_output {{pwd}}/ec2-route.yaml::RouteTablePrivateB
